# Generated by Django 4.2.23 on 2025-10-17 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Courses", "0002_remove_course_image_mise_en_avant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Devoir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("date_limite", models.DateTimeField()),
                (
                    "note",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devoirs",
                        to="Courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_limite"],
            },
        ),
        migrations.CreateModel(
            name="DevoirLien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lien", models.URLField(blank=True)),
                (
                    "fichier",
                    models.FileField(blank=True, null=True, upload_to="devoirs/"),
                ),
                (
                    "devoir",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liens",
                        to="Assignments.devoir",
                    ),
                ),
            ],
        ),
    ]
