# Generated by Django 4.2.23 on 2025-10-17 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Assignments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DevoirSoumis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fichier", models.FileField(upload_to="devoirs_soumis/")),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="devoir",
            name="afficher_soumettre",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="devoir",
            name="liens",
            field=models.TextField(
                blank=True, help_text="Séparer plusieurs liens par des virgules"
            ),
        ),
        migrations.DeleteModel(
            name="DevoirLien",
        ),
        migrations.AddField(
            model_name="devoirsoumis",
            name="devoir",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soumissions",
                to="Assignments.devoir",
            ),
        ),
        migrations.AddField(
            model_name="devoirsoumis",
            name="etudiant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devoirs_soumis",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="devoirsoumis",
            unique_together={("devoir", "etudiant")},
        ),
    ]
