# Generated by Django 4.2.23 on 2025-10-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Assignments",
            "0002_devoirsoumis_devoir_afficher_soumettre_devoir_liens_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="devoir",
            name="promotion",
            field=models.CharField(
                choices=[
                    ("Science de base", "Science de base"),
                    ("Informatique", "Informatique"),
                    ("Mathématiques", "Mathématiques"),
                    ("Physique", "Physique"),
                    ("Chimie", "Chimie"),
                ],
                default="Science de base",
                max_length=50,
            ),
        ),
    ]
