# Generated by Django 5.2.4 on 2025-07-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Nom du cours"),
                ),
                ("code", models.CharField(max_length=15, verbose_name="Code du cour")),
                ("credits", models.IntegerField(verbose_name="Nombre de credits")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "image_mise_en_avant",
                    models.ImageField(upload_to="", verbose_name="Image mise en avant"),
                ),
            ],
            options={
                "verbose_name": "Cour",
                "verbose_name_plural": "Cours",
            },
        ),
    ]
