# Generated by Django 5.2.4 on 2025-07-12 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="image_mise_en_avant",
        ),
    ]
