# Generated by Django 4.2.23 on 2025-10-17 12:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Annonces", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MonModel",
            new_name="Annonce",
        ),
    ]
